export const CountriesMap: { [idx: string]: string } = {
  "United States": "USA",
  Australia: "AUS",
  Greece: "GRC",
  Ethiopia: "ETH",
  "Arabian Peninsula": "ARE",
  "United Kingdom": "GBR",
  Brazil: "BRA",
  France: "FRA",
  Cyprus: "CYP",
  Russia: "RUS",
  China: "CHN",
  Egypt: "EGY",
  Canada: "CAN",
  Japan: "JPN",
  Thailand: "THA",
  Korea: "KOR",
  Norway: "NOR",
  Indonesia: "IDN",
  Singapore: "SGP",
  Kenya: "KEN",
  Somalia: "SOM",
  Ukraine: "UKR",
};
